/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Draggable: typeof import('./src/components/card/draggable/index.vue')['default']
    Mask: typeof import('./src/components/mask/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toobar: typeof import('./src/components/card/draggable/toobar.vue')['default']
    Tray: typeof import('./src/components/navbar/tray.vue')['default']
  }
}
